### ISSUE TITLE
RuntimeError: ALAudioDevice::setClientPreferences ALProxy::ALProxy can't find service: SpeechRecognition

### ISSUE THREAD

**Issue by soumenms2015** [JBramauer/pepperspeechrecognition#2]
Hello,

I am running the below command and I am getting the below error .

python module_speechrecognition.py --pip (robot IP)

INF:SpeecRecognitionModule: starting!
Traceback (most recent call last)
File "module_speechrecognition.py", line 485, in main
SpeechRecognition.start()
File "module_speechrecognition.py", line 127, in start audio.setClientPreferences(self.getName(), SAMPLE_RATE, nNbrChannelFlag, nDeinterleave) ' setting same as default generate a bus !?!
File "C:Python27\Lib\site-packages\lib\naoqi.py", line 264, in method_missing 
   
    raise e
RuntimeError: ALAudioDevice::setClientPreferences
         ALProxy::AlProxy
    can't find service: SpeechRecognition
INF: SpeechRecognitionModule.__del__: cleaning everything
INF: SpeechRecognitionModule.pause: stopping
Exception AttributeError: "NoneType' object has no attribute 'ALProxy'" in <bound method SpeechRecognitionModule.__del__ of <__main__.SpeechRecognitionModule; proxy of <Swig Object of type 'AL::module *' at 0x06870278> >> ignored

any idea behind this error? 

Thank you !!!!

N.B: I have also installed pip install speechrecogintion package but that doesnt fiy the issue.

**Comment by JBramauer** [comment]
Just to make sure - you did replace (robot IP) with the actual IP address of the robot?
I don't have access to a robot atm so i cannot test the script against the latest robot software version and sdk version, but maybe we can fix this together.

"setting same as default generate a bus !?!" did you write this or is this from the console output?

**Comment by soumenms2015** [comment]
Hello Johannes,

I have replaced the robot IP in module_receiver.py and also pass the robot IP via command line argument.
"setting same as default generate a bus ! what do you mean by this?

The issue I have posted, I had to write it as I am using windows cmd. Of cours this is complete error which I have found while running this.
I am going to write via gmail id. Let's catch via hangout call. That would be great!!

**Comment by YifengMa9** [comment]
I encounter the same problem, so is there any solution?

**Comment by JBramauer** [comment]
I'm sorry, but I don't have access to a pepper robot any more. I will accept pull requests. Maybe someone who forked the project already implemented a fix?

**Comment by YifengMa9** [comment]
Thank you all the same

**Comment by Showwwwwwwww** [comment]
> I encounter the same problem, so is there any solution?

Hi Yifeng, Can I know have you solved it? I am encountering the same as well.

**Comment by BirkHintzeThisted** [comment]
I have the same issue from a forked project (that apparently once worked).

The code fails at:
`audio.setClientPreferences(self.getName(), SAMPLE_RATE, nNbrChannelFlag, nDeinterleave)`
