### ISSUE TITLE
Can't find service: SpeechRecognition

### ISSUE THREAD

**Issue by E21009MH** [JBramauer/pepperspeechrecognition#4]
Hello,

Hello,

I recently wanted to get speech recognition up and running for a student research project. However, I have encountered a few problems that I have not yet been able to solve. The error has something to do with the Speecregognition method, which could not be found. Hence the question of whether anyone has ever had the same error and found a solution.

Thank you very much for your help.
The following error occurs: 

_Traceback (most recent call last):
  File "module_receiver.py", line 154, in <module>
    main()
  File "module_receiver.py", line 130, in main
    SpeechRecognition.start()
  File "D:\_Studium\5. Semester\Studienarbeit\Python_SDK\pynaoqi-python2.7-2.5.7.1-win32-vs2013\lib\naoqi.py", line 194, in __call__
    return self.__wrapped__.method_missing(self.__method__, *args, **kwargs)
  File "D:\_Studium\5. Semester\Studienarbeit\Python_SDK\pynaoqi-python2.7-2.5.7.1-win32-vs2013\lib\naoqi.py", line 264, in method_missing
    raise e
RuntimeError:   SpeechRecognition::start
                ALPythonModule::execute
        calling SpeechRecognition.start
<type 'exceptions.RuntimeError'>
        ALAudioDevice::setClientPreferences
                ALProxy::ALProxy
        Can't find service: SpeechRecognition
INF: ReceiverModule.__del__: cleaning everything
INF: ReceiverModule: stopping...
Exception NotImplementedError: "Wrong number or type of arguments for overloaded function 'new_proxy'.\n  Possible C/C++ prototypes are:\n    AL::proxy(char *)\n    AL::proxy(char *,bool)\n    AL::proxy(char *,char *,int,bool)\n    AL::proxy(char *,char *,int)\n" in <bound method BaseSpeechReceiverModule.__del__ of <__main__.BaseSpeechReceiverModule; proxy of <Swig Object of type 'AL::module *' at 0x02944E78> >> ignored_

**Comment by BirkHintzeThisted** [comment]
I've been able to narrow it down. I'm debugging a project that forked it.

It fails at (in the speechrecognition.py file.):

`audio.setClientPreferences(self.getName(), SAMPLE_RATE, nNbrChannelFlag, nDeinterleave)
`

I've been able to confirm that the service is running on the pepper robot.

If anyone has some insight, it would be much appreciated.
